### ISSUE TITLE
Just to say - endless problems with Broadcom - our solution - rid ourselves of them.

### ISSUE THREAD

**Issue by sammcj** [hlandau/ortega#1]
Old post now, but all our network issues went away across multiple platforms and hardware when we removed Broadcom NICs from every server: https://smcleod.net/tech/2017/10/13/Drop-Broadcom.html

![office-space-broadcom](https://user-images.githubusercontent.com/862951/58143603-b7a8bd00-7c8e-11e9-8109-f2dd9524a1e1.jpg)

(I even have fridge magnets of this!)

**Comment by hlandau** [comment]
I assume you read [this](https://github.com/hlandau/ortega/blob/master/rtg-spec.md#fucking-broadcom)... welcome to the *FFS Broadcom* club. :man_facepalming:

**Comment by sammcj** [comment]
Oh man... yeah... so glad I rid myself of them!
